/** @type {import('tailwindcss').Config} */
import daisyui from 'daisyui';
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--primary-color, #6366f1)",
      }
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        bondbeyond: {
          "primary": "oklch(65% 0.25 265)",
          "secondary": "oklch(70% 0.2 340)",
          "accent": "oklch(75% 0.15 150)",
          "neutral": "oklch(25% 0.05 265)",
          "base-100": "oklch(100% 0 0)",
          "base-200": "oklch(98% 0.01 265)",
          "base-300": "oklch(95% 0.02 265)",
          "base-content": "oklch(30% 0.05 265)",
          "info": "oklch(70% 0.1 200)",
          "success": "oklch(70% 0.15 150)",
          "warning": "oklch(80% 0.15 70)",
          "error": "oklch(65% 0.2 25)",
          "--rounded-box": "2rem",
          "--rounded-btn": "1rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
        },
        bondbeyonddark: {
          "primary": "oklch(70% 0.2 265)",
          "secondary": "oklch(75% 0.15 340)",
          "accent": "oklch(80% 0.1 150)",
          "neutral": "oklch(20% 0.05 265)",
          "base-100": "oklch(15% 0.02 265)",
          "base-200": "oklch(12% 0.02 265)",
          "base-300": "oklch(10% 0.02 265)",
          "base-content": "oklch(90% 0.02 265)",
          "info": "oklch(75% 0.1 200)",
          "success": "oklch(75% 0.15 150)",
          "warning": "oklch(85% 0.15 70)",
          "error": "oklch(70% 0.2 25)",
          "--rounded-box": "2rem",
          "--rounded-btn": "1rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
        },
      },
      "light",
      "dark",
      "cupcake",
      "forest",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  }, 
};