services:
  - type: web
    name: freechat-web-1
    env: node
    plan: free
    buildCommand: "npm install && npm run build --prefix frontend"
    startCommand: "node backend/src/server.js"
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
